version: '1'
services:
  postgres_db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - /var/mount/imageAPI/postgre_db/data:/var/lib/postgresql/data
      - /var/mount/imageAPI/postgre_db/log:/var/log/
    ports:
      - "5432:5432"
  django:
    build: ./
    environment:
     - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
    - "10301:80"
    depends_on:
      - postgres_db
