# Generated by Django 3.2.5 on 2021-07-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_widget_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Ключ')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.widget', verbose_name='Виджет')),
            ],
        ),
    ]
