# Generated by Django 3.2.5 on 2021-07-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_widgetconfigurationitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetconfigurationitem',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.RemoveField(
            model_name='widget',
            name='configurations',
        ),
    ]
