# Generated by Django 3.2.5 on 2021-07-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_widgetconfigurationitem_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfigurationitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.site'),
        ),
    ]
